name: lobehub
services:
  network-service:
    image: alpine
    container_name: lobe-network
    restart: always
    ports:
      - '${MINIO_PORT:-9000}:9000' # MinIO API
      - '9001:9001' # MinIO Console
      - '${LOBE_PORT}:3210' # LobeChat
    command: tail -f /dev/null
    networks:
      - lobe-network
    env_file:
      - .env

  postgresql:
    image: paradedb/paradedb:latest-pg17
    container_name: lobe-postgres
    ports:
      - '5432:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - lobe-network
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: lobe-redis
    ports:
      - '6379:6379'
    command: redis-server --save 60 1000 --appendonly yes
    volumes:
      - 'redis_data:/data'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
    networks:
      - lobe-network

  minio:
    image: minio/minio:latest
    container_name: lobe-minio
    network_mode: 'service:network-service'
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_API_CORS_ALLOW_ORIGIN=*
    volumes:
      - minio-data:/data
      - ./bucket.config.json:/bucket.config.json:ro
    healthcheck:
      test: ['CMD-SHELL', 'curl -s http://localhost:9000/minio/health/live >/dev/null 2>&1 || exit 1']
      interval: 5s
      timeout: 3s
      retries: 30
    entrypoint: >
      /bin/sh -c "
        minio server /data --address ':9000' --console-address ':9001' &
        MINIO_PID=$$!;
        while ! curl -s http://localhost:9000/minio/health/live; do
          echo 'Waiting for MinIO to start...';
          sleep 1;
        done;
        sleep 3;
        mc alias set myminio http://localhost:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        mc mb myminio/${MINIO_LOBE_BUCKET} --ignore-existing;
        mc anonymous set-json /bucket.config.json myminio/${MINIO_LOBE_BUCKET};
        wait $$MINIO_PID;
      "
    env_file:
      - .env

  searxng:
    image: searxng/searxng
    container_name: lobe-searxng
    ports:
      - '8180:8080'
    volumes:
      - './searxng-settings.yml:/etc/searxng/settings.yml'
    environment:
      - 'SEARXNG_SETTINGS_FILE=/etc/searxng/settings.yml'
    restart: always
    networks:
      - lobe-network

volumes:
  data:
    driver: local
  redis_data:
    driver: local
  minio-data:
    driver: local

networks:
  lobe-network:
    driver: bridge
